# Generated by Django 5.1.2 on 2024-10-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='buyer',
            field=models.ManyToManyField(blank=True, null=True, related_name='medicines', to='myshop.buyer'),
        ),
    ]
